{
 "title": "MeshFlux",
 "description": "Meshtastic Nodes from InfluxDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\r\n  |> keyValues(keyColumns: [\"${NodeIdentifier}\"])\r\n  |> group()\r\n  |> keep(columns: [\"${NodeIdentifier}\"])\r\n  |> distinct(column: \"${NodeIdentifier}\")\r\n\r\n"
    }
   },
   { "name": "Bucket", "query": "influx_bucket" },
   {
    "name": "NodeIdentifier",
    "label": "Node Grouping",
    "query": "short_name, long_name, mac_address, id, hw_model"
   },
   { "name": "Measurement", "query": "influx_measurement" },
   {
    "name": "DisplayName",
    "label": "Display Name",
    "query": "${NodeIdentifier}, short_name, long_name, mac_address, id"
   },
   {
    "name": "DiscoveredBy",
    "label": "Discovered By",
    "query": {
     "query": "import \"array\"\r\n\r\n// Fetch unique discovered_by entries\r\ndiscovered_by = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\r\n  |> keyValues(keyColumns: [\"discovered_by\"])\r\n  |> group()\r\n  |> keep(columns: [\"discovered_by\"])\r\n  |> unique(column: \"discovered_by\")\r\n  |> map(fn: (r) => ({r with id: r.discovered_by}))\r\n  //|> yield(name: \"discovered_by\")\r\n\r\n// Fetch unique node names along with their associated id and short_name\r\nnode_names = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\r\n  |> keyValues(keyColumns: [\"${NodeIdentifier}\"])\r\n  |> group()\r\n  |> keep(columns: [\"id\", \"${NodeIdentifier}\"])\r\n  |> unique(column: \"id\")\r\n\r\n// Join the data to get discovered_by entries with their corresponding short_name\r\njoined_data = join(\r\n  tables: {discovered: discovered_by, nodes: node_names},\r\n  on: [\"id\"],\r\n  method: \"inner\"\r\n)\r\n  |> keep(columns: [\"${NodeIdentifier}\"])\r\n\r\n// Create a table with a single row containing 'all'\r\nall_entry = array.from(rows: [{${NodeIdentifier}: \"All Nodes\"}])\r\n\r\n// Combine the 'all' entry with the joined data\r\nfinal_data = union(tables: [joined_data, all_entry])\r\n\r\n// Yield the final result\r\nfinal_data |> yield(name: \"unique_discovered_by_with_short_name\")"
    }
   },
   {
    "name": "DiscoveredById",
    "label": "Discovered By Id",
    "query": {
     "query": "discovered_by = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\r\n  |> keyValues(keyColumns: [\"discovered_by\"])\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${DiscoveredBy:regex}/)\r\n  //|> filter(fn: (r) => r.${NodeIdentifier} == \"${DiscoveredBy}\")\r\n  |> group()\r\n  |> keep(columns: [\"id\"])\r\n  |> unique(column: \"id\")\r\n  \r\n  |> yield(name: \"discovered_by\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pos_latitude\" or r[\"_field\"] == \"pos_longitude\" or r[\"_field\"] == \"snr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.pos_latitude and exists r.pos_longitude and exists r.snr)\r\n  |> group(columns: [\"${NodeIdentifier}\"])\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  //|> yield(name: \"original\")\r\n\r\ndata = bucket1\r\n  |> sort(columns: [\"${NodeIdentifier}\", \"_time\"])\r\n\r\ndatadiff = data\r\n  |> difference(columns: [\"pos_longitude\", \"pos_latitude\"])\r\n  |> map(fn: (r) => ({r with \r\n     aDiff: math.abs(x: r.pos_longitude),\r\n     bDiff: math.abs(x: r.pos_latitude)\r\n     }))\r\n  |> drop(columns: [\"pos_longitude\", \"pos_latitude\"])\r\n  //|> yield()\r\n\r\ndatafinal = join.tables(method: \"inner\", left: data, right: datadiff, on: (l, r) => l._time == r._time, as: (l, r) => ({l with latdiff: r.aDiff, londiff: r.bDiff}),)\r\n  |> filter(fn: (r) => (r._time > date.truncate(t: now(), unit: 30m)) or (r.latdiff >= 0.007 or r.londiff >= 0.007))\r\n  |> drop(columns: [\"latdiff\", \"londiff\"])\r\n  |> group()\r\n  |> yield(name: \"final\")"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbasePipeline = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n\r\n// Conditionally apply the 'drop' function or filter with regex based on the variable\r\nfinalPipeline = if \"${DiscoveredById}\" != \"\" then basePipeline |> filter(fn: (r) => r[\"discovered_by\"] =~ /${DiscoveredById:regex}/) else basePipeline |> drop(columns: [\"discovered_by\"])\r\nfinalPipeline\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  },
  {
   "title": "Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbasePipeline = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"channel_utilization\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n\r\n// Conditionally apply the 'drop' function or filter with regex based on the variable\r\nfinalPipeline = if \"${DiscoveredById}\" != \"\" then basePipeline |> filter(fn: (r) => r[\"discovered_by\"] =~ /${DiscoveredById:regex}/) else basePipeline |> drop(columns: [\"discovered_by\"])\r\nfinalPipeline\r\n  |> yield(name: \"data\")"
    }
   ]
  },
  {
   "title": "Air Utilization TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbasePipeline = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_util_tx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n\r\n// Conditionally apply the 'drop' function or filter with regex based on the variable\r\nfinalPipeline = if \"${DiscoveredById}\" != \"\" then basePipeline |> filter(fn: (r) => r[\"discovered_by\"] =~ /${DiscoveredById:regex}/) else basePipeline |> drop(columns: [\"discovered_by\"])\r\nfinalPipeline\r\n  |> yield(name: \"data\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbasePipeline = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n\r\n// Conditionally apply the 'drop' function or filter with regex based on the variable\r\nfinalPipeline = if \"${DiscoveredById}\" != \"\" then basePipeline |> filter(fn: (r) => r[\"discovered_by\"] =~ /${DiscoveredById:regex}/) else basePipeline |> drop(columns: [\"discovered_by\"])\r\nfinalPipeline\r\n  |> yield(name: \"data\")"
    }
   ]
  },
  {
   "title": "Licensed radios",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"is_licensed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\", \"discovered_by\"])\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> unique(column: \"${NodeIdentifier}\")\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  }
 ]
}