{
 "title": "MeshFlux",
 "description": "Meshtastic Nodes from InfluxDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\r\n  |> keyValues(keyColumns: [\"${NodeIdentifier}\"])\r\n  |> group()\r\n  |> keep(columns: [\"${NodeIdentifier}\"])\r\n  |> distinct(column: \"${NodeIdentifier}\")\r\n\r\n"
    }
   },
   { "name": "Bucket", "query": "python-scraping" },
   {
    "name": "NodeIdentifier",
    "label": "Node Identifier",
    "query": "short_name, long_name, mac_address, id, hw_model"
   },
   { "name": "Measurement", "query": "meshtastic_node" },
   {
    "name": "DisplayName",
    "label": "Display Name",
    "query": "${NodeIdentifier}, short_name, long_name, mac_address, id"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pos_latitude\" or r[\"_field\"] == \"pos_longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"${NodeIdentifier}\"])\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  //|> yield(name: \"original\")\r\n\r\n//bucket2 = from(bucket: \"${InfluxBucket_ds}\")\r\n//  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n//  |> filter(fn: (r) => r[\"entity_id\"] =~ /${person:regex}/)\r\n//  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n//  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n//  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n//  |> group()\r\n\r\ndata = bucket1\r\n  |> sort(columns: [\"${NodeIdentifier}\", \"_time\"])\r\n\r\n//data = union(tables: [bucket1, bucket2])\r\n//  |> sort(columns: [\"friendly_name\", \"_time\"])\r\n  //|> yield(name: \"original\")\r\n\r\ndatadiff = data\r\n  |> difference(columns: [\"pos_longitude\", \"pos_latitude\"])\r\n  |> map(fn: (r) => ({r with \r\n     aDiff: math.abs(x: r.pos_longitude),\r\n     bDiff: math.abs(x: r.pos_latitude)\r\n     }))\r\n  |> drop(columns: [\"pos_longitude\", \"pos_latitude\"])\r\n  //|> yield()\r\n\r\ndatafinal = join.tables(method: \"inner\", left: data, right: datadiff, on: (l, r) => l._time == r._time, as: (l, r) => ({l with latdiff: r.aDiff, londiff: r.bDiff}),)\r\n  |> filter(fn: (r) => r._time > date.truncate(t: now(), unit: 30m) or r.latdiff >= 0.007 or r.londiff >= 0.007)\r\n  |> group()\r\n  |> yield(name: \"final\")"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  },
  {
   "title": "Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"channel_utilization\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  },
  {
   "title": "Air Utilization TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_util_tx\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  },
  {
   "title": "Licensed radios",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//import \"timezone\"\r\nimport \"join\"\r\nimport \"math\"\r\nimport \"date\"\r\n//option location = timezone.fixed(offset: ${TimeZone})\r\n\r\nbucket1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"${NodeIdentifier}\"] =~ /${Node:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"is_licensed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n  |> map(fn: (r) => ({r with short_name: r.${DisplayName}}))\r\n  |> yield(name: \"data\")\r\n"
    }
   ]
  }
 ]
}